### ISSUE TITLE
Prevent bolding/enlargment on cell selection

### ISSUE THREAD

**Issue by zebaslam** [openfin/fin-hypergrid#372]
Is there a way to prevent bolding/enlarging on cell selection without using the cellSection: false which doesnt allow the person to select at all? 
Sample fiddle:
https://jsfiddle.net/zaslam/k5bdh7o3/

**Comment by noahtaylor** [comment]
@zebaslam I think you can use the  foregroundSelectionFont property for the hypergrid
e.g. '12px Tahoma, Geneva, sans-serif',

**Comment by zebaslam** [comment]
@noahtaylor That definitely helped with the bold issue! Thanks!

However, Im still seeing the columns being enlarged
Updated fiddle: https://jsfiddle.net/zaslam/k5bdh7o3/4/

**Comment by Dwaynekj** [comment]
@zebaslam We can take at your issue tomorrow

**Comment by noahtaylor** [comment]
@zebaslam more font issues.  check out:
https://jsfiddle.net/k5bdh7o3/5/

You need to set all the fonts consistently, otherwise columns will auto resize based on the fonts changing to bold e.g. 
columnHeaderFont:'12px Tahoma, Geneva, sans-serif',
font:'12px Tahoma, Geneva, sans-serif',
columnHeaderForegroundSelectionFont:'12px Tahoma, Geneva, sans-serif'

**Comment by zebaslam** [comment]
This is way better! Thanks @noahtaylor
