### ISSUE TITLE
Custom graphics functions

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#537]
I'd like to do:
`grid.canvas.gc.simpleText = grid.canvas.bc.simpleText = renderText;`
with:
```
        function renderText(config, str, x, y) {
            var gc = this;
            if (config.someCondition) {
                some_complex_function(config, str, x, y);
            } else {
                gc.fillText(str, x, y);
            }
        }
```

The problem is that the fillText function has disappeared when I inspect the gc object in my browser so i can't render anything.

In addition, I only want to render text using this method for a subset of columns because I don't want to incur any unecessary performance costs for the columns that should not be affected by this special rendering.

How should I approach?

At the moment, I have created a new renderer and I have copied the whole code of SimpleCell to only replace the calls to gc.simpleText with my function and I assign that new renderer only for the columns that should be affected.

Bonus neophyte question, what's the difference between grid.canvas.gc and grid.canvas.bc?

**Comment by Dwaynekj** [comment]
@nclsclsn We will get back to next week, sorry for the delay

**Comment by Dwaynekj** [comment]
@joneit Can you address his question?

**Comment by joneit** [comment]
Nicolas, I apologize for the delay in responding.

1. I could not reproduce you're issue; my function _does_ have access to `this.fillText`. Have you since figured out what led you to believe it was missing?

2. Regarding `bc`, it is an alternate, off-screen canvas object. When `grid.properties.useBitBlit` is truthy, graphics are rendered into `bc` instead of `gc` and then the entire canvas is copied in one "blitter" operation to `gc`.The previous developer claimed it resulted in faster renderering.

Jonathan
