### ISSUE TITLE
MultiLevel Schema

### ISSUE THREAD

**Issue by eibertek** [openfin/fin-hypergrid#607]
Hi all, Im needing to create a multi level schema like:

```
Item1 | Item2 | Item3 |                Item4           |
      |       |       | subitem1 | subitem2 | subitem3 |

```
Im looking the schema object but Its seems its only defer an array. If there any way to create something like this?

Thanks!

**Comment by joneit** [comment]
### Flat data structure
You are correct: Our data model currently only works with (an array of) flat objects (one per row).

### Core dependences
Furthermore, there are a few spots in the Hypergrid core that depend on this flat data structure.

### New data model in development
However, we are currently isolating and simplifying the data model and removing those dependencies. This means you could conceivably write your own data model module to accommodate your use case (hierarchical data structure).

### Workaround
In the meantime, you might be able to work around this limitation by:
1. flattening your data, perhaps using dot syntax, before sending
2. use the grouped headers plugin to get the kind of output suggested by your data diagram

#### Flatten your data
Before PUTing your data, transform to a flat structure, perhaps using dot syntax.

For example, rather than sending (where "..." represents data):
```
[
    {
        "Item1": ...,
        "Item2": ...,
        "Item3": ...,
        "Item4": {
            "subitem1": ...,
            "subitem2": ...,
            "subitem3": ...
        }
    },
    ...
]
```
send this instead:
```
[
    {
        "Item1": ...,
        "Item2": ...,
        "Item3": ...,
        "Item4.subitem1": ...,
        "Item4.subitem2": ...,
        "Item4.subitem3": ...
    },
    ...
]
```

#### Use the grouped headers plugin
This plugin renders grouped column headers (to any depth). There are several options, but the only requirement is a map, which for the above example would look like this:
```js
grid.behavior.getActiveColumn[0].header = "Name|First";
grid.behavior.getActiveColumn[1].header = "Name|Last";
```
Hypergrid plugins are currently being moved to a new home ([repo](https://github.com/fin-hypergrid/grouped-headers-plugin)). See the readme for plugin for a link to the API docs and for installation and usage details. (If this link is not working yet, download [this zip file](http://cdn.openfin.co/download/fin-hypergrid-grouped-header-demo-master.zip). You'll have to wait for the wiki and the associated docs. In the meantime you can read the jsdoc comments.)

**Comment by eibertek** [comment]
You are awesome!!! thanks a lot!
