### ISSUE TITLE
How can I use this fin-hypergrid in BackboneJS

### ISSUE THREAD

**Issue by abdulwahid24** [openfin/fin-hypergrid#83]
Hi,

I tried to find out the installation documentation for javascript project but couldn't find any. Can any one guide me how can I integrate `fin-hypergrid` into my backbone project.

Thanks.

**Comment by joneit** [comment]
Abdul, Thanks for contacting us. We are on skeleton crew today. We will
respond with details on Monday. In the mean time, have a good New Year's.

On Thu, Dec 31, 2015 at 5:08 AM, Abdul Wahid <notifications@github.com>
wrote:

> Hi,
>
> I tried to find out the installation documentation for javascript project
> but couldn't find any. Can any one guide me how can I integrate
> fln-hypergrid into my backbone project.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfin/fin-hypergrid/issues/83>.
>



-- 




*Jonathan EitenSenior Developer | OpenFin201-674-1457
<201-674-1457>jonathan@openfin.co <jonathan@openfin.co>Extend. Integrate.
Deploy.www.openfin.co <http://www.openfin.co/> | @openfintech**Skype:
jonaverse*
*Twitter: @JonathanEiten*
*LinkedIn: http://www.linkedin.com/in/jonathaneiten
<http://www.linkedin.com/in/jonathaneiten>*

**Comment by abdulwahid24** [comment]
@joneit Let me know If you are available, so that we can have some discussion about this

**Comment by joneit** [comment]
Abdul,

Thank you for your patience.

We are working hard to release Hypergrid 2 later this month. You might want to wait for v.2 because it has much expanded functionality. We have also removed the polymer requirement making it simpler to deploy.

If you don't want to wait, you can use the existing version. The basic set up as explained in the readme on [the hypergrid repo page in Github](https://github.com/openfin/fin-hypergrid) is just a few steps:

1. Download either of the following files an make them available on your server:

* https://github.com/openfin/fin-hypergrid/blob/master/fin-hypergrid.dev.html
* https://github.com/openfin/fin-hypergrid/blob/master/fin-hypergrid.min.html

2. In your HTML file, inside the `<head>...</head>` element, reference one of the above files in a `<link/>` element, for example:

```html
<link rel="import" id="your-grid" href="fin-hypergrid.min.html">
```

3. In your HTML file, inside the `<body>...</body>` element, add a `<hypergrid>...</hypergrid>` element where you want the grid to appear. You should size it appropriately.

4. In your .js file, you make a reference to the hypergrid object. All the methods are then accessible:

```javascript
var inMemoryGrid = document.querySelector('#your-grid');
```

Note that you can see steps 2, 3, and 4 in [our example](http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/demo.html), lines 49 and 171, and 359, respectively.

Caveat: If you need this to work in non-Chrome browsers, you must include the Polymer polyfill ([example](https://github.com/openfin/example-fin-hypergrid-behavior-json)):

```html
<script src="webcomponents.js"></script>
````

Thank you for your interest.

J. Eiten

**Comment by abdulwahid24** [comment]
Thanks @joneit for detailed informations. Its really helpful. :+1:
